// Builds the stylesheet the Claude Design bundle ships: the app's compiled
// Tailwind output (globals.css run through the app's own tailwind.config.ts,
// so every utility the app uses is present), with the two Google Fonts the
// app loads through next/font declared up front. Output is gitignored and
// regenerated by design-sync's buildCmd.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const web = join(root, "apps", "web");
const outDir = join(web, ".ds-css");
mkdirSync(outDir, { recursive: true });

const bin = join(root, "node_modules", ".bin", process.platform === "win32" ? "tailwindcss.CMD" : "tailwindcss");
execFileSync(bin, ["-c", "tailwind.config.ts", "-i", "src/app/globals.css", "-o", join(outDir, "tailwind.css"), "--content", "./src/**/*.{ts,tsx},../../.design-sync/previews/*.tsx"], {
  cwd: web,
  stdio: "inherit",
  shell: process.platform === "win32",
});

const header = [
  '@import url("https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap");',
  "",
  "/* next/font sets these on <body> in the app; the bundle declares them once. */",
  ":root {",
  '  --font-sans: "Source Sans 3";',
  '  --font-display: "Oswald";',
  "}",
  "",
].join("\n");

writeFileSync(join(outDir, "styles.css"), header + readFileSync(join(outDir, "tailwind.css"), "utf8"));
console.error(`  css: wrote ${join(outDir, "styles.css")}`);
