// Generated by the Supabase type generator — DO NOT EDIT BY HAND.
// Source: Supabase project rwpglslbkhsqyxjhnpue (aomsc-function-room), 2026-08-21 (P0.2 baseline).
// Regenerate with: pnpm --filter @club/db gen:types
// PLAN §2.7: regenerate this file in the same PR as any migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          created_at: string
          detail: Json | null
          entity: string
          entity_id: string | null
          id: number
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          detail?: Json | null
          entity: string
          entity_id?: string | null
          id?: never
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          detail?: Json | null
          entity?: string
          entity_id?: string | null
          id?: never
        }
        Relationships: []
      }
      bank_holidays: {
        Row: {
          approved: boolean
          created_at: string
          date: string
          id: string
          source: string
          title: string
        }
        Insert: {
          approved?: boolean
          created_at?: string
          date: string
          id?: string
          source?: string
          title: string
        }
        Update: {
          approved?: boolean
          created_at?: string
          date?: string
          id?: string
          source?: string
          title?: string
        }
        Relationships: []
      }
      booking_comms: {
        Row: {
          body: string | null
          booking_id: string
          cc: string | null
          channel: string
          id: string
          kind: string
          legacy_booking_email_id: string | null
          sent_at: string
          sent_by: string | null
          sent_by_name: string | null
          subject: string
          to_address: string
        }
        Insert: {
          body?: string | null
          booking_id: string
          cc?: string | null
          channel?: string
          id?: string
          kind?: string
          legacy_booking_email_id?: string | null
          sent_at?: string
          sent_by?: string | null
          sent_by_name?: string | null
          subject: string
          to_address: string
        }
        Update: {
          body?: string | null
          booking_id?: string
          cc?: string | null
          channel?: string
          id?: string
          kind?: string
          legacy_booking_email_id?: string | null
          sent_at?: string
          sent_by?: string | null
          sent_by_name?: string | null
          subject?: string
          to_address?: string
        }
        Relationships: [
          {
            foreignKeyName: "booking_comms_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      booking_emails: {
        Row: {
          body: string | null
          booking_id: string
          cc: string | null
          id: string
          kind: string
          sent_at: string
          sent_by: string | null
          sent_by_name: string | null
          subject: string
          to_email: string
        }
        Insert: {
          body?: string | null
          booking_id: string
          cc?: string | null
          id?: string
          kind?: string
          sent_at?: string
          sent_by?: string | null
          sent_by_name?: string | null
          subject: string
          to_email: string
        }
        Update: {
          body?: string | null
          booking_id?: string
          cc?: string | null
          id?: string
          kind?: string
          sent_at?: string
          sent_by?: string | null
          sent_by_name?: string | null
          subject?: string
          to_email?: string
        }
        Relationships: [
          {
            foreignKeyName: "booking_emails_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "room_bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      booking_payments: {
        Row: {
          amount_pence: number
          authorised_by_email: string | null
          authorised_by_name: string | null
          authorised_by_profile: string | null
          booking_id: string
          created_at: string
          id: string
          method: string | null
          note: string | null
          paid_at: string
          reference: string | null
          source: string
          sumup_checkout_id: string | null
          sumup_txn_code: string | null
        }
        Insert: {
          amount_pence: number
          authorised_by_email?: string | null
          authorised_by_name?: string | null
          authorised_by_profile?: string | null
          booking_id: string
          created_at?: string
          id?: string
          method?: string | null
          note?: string | null
          paid_at?: string
          reference?: string | null
          source?: string
          sumup_checkout_id?: string | null
          sumup_txn_code?: string | null
        }
        Update: {
          amount_pence?: number
          authorised_by_email?: string | null
          authorised_by_name?: string | null
          authorised_by_profile?: string | null
          booking_id?: string
          created_at?: string
          id?: string
          method?: string | null
          note?: string | null
          paid_at?: string
          reference?: string | null
          source?: string
          sumup_checkout_id?: string | null
          sumup_txn_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "booking_payments_authorised_by_profile_fkey"
            columns: ["authorised_by_profile"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "booking_payments_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "room_bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          anonymised_at: string | null
          balance_due_date: string | null
          balance_reminder_sent_at: string | null
          base_hire_pence: number
          blocked_from: string
          blocked_until: string
          booker_email: string
          booker_first_name: string | null
          booker_last_name: string | null
          booker_name: string
          booker_person_id: string | null
          booker_phone: string | null
          booker_profile_id: string | null
          calendar_event_id: string | null
          cancellation_warning_sent_at: string | null
          child_name: string | null
          child_team: string | null
          confirmation_note: string | null
          created_at: string
          created_by: string | null
          deposit_due_date: string | null
          deposit_pence: number | null
          deposit_reminder_sent_at: string | null
          deposit_terms_accepted_at: string | null
          ends_at: string
          estimated_guests: number | null
          extras_total_pence: number
          id: string
          internal_notes: string | null
          is_member: boolean
          kind: Database["public"]["Enums"]["booking_kind"]
          legacy_room_booking_id: string | null
          member_discount_pence: number
          member_number: string | null
          membership_type: string | null
          notes: string | null
          occasion: string | null
          payment_method: string | null
          payment_received_at: string | null
          payment_received_by: string | null
          payment_reference: string | null
          payment_status: Database["public"]["Enums"]["payment_status"]
          post_buffer_minutes: number
          pre_buffer_minutes: number
          quote_followup_sent_at: string | null
          recurrence_group_id: string | null
          resource_id: string
          security_deposit_nudge_sent_at: string | null
          security_deposit_pence: number
          security_deposit_returned_at: string | null
          security_deposit_returned_method: string | null
          security_deposit_returned_note: string | null
          selected_extras: Json
          starts_at: string
          status: Database["public"]["Enums"]["booking_status"]
          stripe_checkout_id: string | null
          stripe_ref: string | null
          team_name: string | null
          thank_you_sent_at: string | null
          total_pence: number | null
          updated_at: string
        }
        Insert: {
          anonymised_at?: string | null
          balance_due_date?: string | null
          balance_reminder_sent_at?: string | null
          base_hire_pence?: number
          blocked_from: string
          blocked_until: string
          booker_email: string
          booker_first_name?: string | null
          booker_last_name?: string | null
          booker_name: string
          booker_person_id?: string | null
          booker_phone?: string | null
          booker_profile_id?: string | null
          calendar_event_id?: string | null
          cancellation_warning_sent_at?: string | null
          child_name?: string | null
          child_team?: string | null
          confirmation_note?: string | null
          created_at?: string
          created_by?: string | null
          deposit_due_date?: string | null
          deposit_pence?: number | null
          deposit_reminder_sent_at?: string | null
          deposit_terms_accepted_at?: string | null
          ends_at: string
          estimated_guests?: number | null
          extras_total_pence?: number
          id?: string
          internal_notes?: string | null
          is_member?: boolean
          kind?: Database["public"]["Enums"]["booking_kind"]
          legacy_room_booking_id?: string | null
          member_discount_pence?: number
          member_number?: string | null
          membership_type?: string | null
          notes?: string | null
          occasion?: string | null
          payment_method?: string | null
          payment_received_at?: string | null
          payment_received_by?: string | null
          payment_reference?: string | null
          payment_status?: Database["public"]["Enums"]["payment_status"]
          post_buffer_minutes?: number
          pre_buffer_minutes?: number
          quote_followup_sent_at?: string | null
          recurrence_group_id?: string | null
          resource_id: string
          security_deposit_nudge_sent_at?: string | null
          security_deposit_pence?: number
          security_deposit_returned_at?: string | null
          security_deposit_returned_method?: string | null
          security_deposit_returned_note?: string | null
          selected_extras?: Json
          starts_at: string
          status?: Database["public"]["Enums"]["booking_status"]
          stripe_checkout_id?: string | null
          stripe_ref?: string | null
          team_name?: string | null
          thank_you_sent_at?: string | null
          total_pence?: number | null
          updated_at?: string
        }
        Update: {
          anonymised_at?: string | null
          balance_due_date?: string | null
          balance_reminder_sent_at?: string | null
          base_hire_pence?: number
          blocked_from?: string
          blocked_until?: string
          booker_email?: string
          booker_first_name?: string | null
          booker_last_name?: string | null
          booker_name?: string
          booker_person_id?: string | null
          booker_phone?: string | null
          booker_profile_id?: string | null
          calendar_event_id?: string | null
          cancellation_warning_sent_at?: string | null
          child_name?: string | null
          child_team?: string | null
          confirmation_note?: string | null
          created_at?: string
          created_by?: string | null
          deposit_due_date?: string | null
          deposit_pence?: number | null
          deposit_reminder_sent_at?: string | null
          deposit_terms_accepted_at?: string | null
          ends_at?: string
          estimated_guests?: number | null
          extras_total_pence?: number
          id?: string
          internal_notes?: string | null
          is_member?: boolean
          kind?: Database["public"]["Enums"]["booking_kind"]
          legacy_room_booking_id?: string | null
          member_discount_pence?: number
          member_number?: string | null
          membership_type?: string | null
          notes?: string | null
          occasion?: string | null
          payment_method?: string | null
          payment_received_at?: string | null
          payment_received_by?: string | null
          payment_reference?: string | null
          payment_status?: Database["public"]["Enums"]["payment_status"]
          post_buffer_minutes?: number
          pre_buffer_minutes?: number
          quote_followup_sent_at?: string | null
          recurrence_group_id?: string | null
          resource_id?: string
          security_deposit_nudge_sent_at?: string | null
          security_deposit_pence?: number
          security_deposit_returned_at?: string | null
          security_deposit_returned_method?: string | null
          security_deposit_returned_note?: string | null
          selected_extras?: Json
          starts_at?: string
          status?: Database["public"]["Enums"]["booking_status"]
          stripe_checkout_id?: string | null
          stripe_ref?: string | null
          team_name?: string | null
          thank_you_sent_at?: string | null
          total_pence?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookings_booker_person_id_fkey"
            columns: ["booker_person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_booker_profile_id_fkey"
            columns: ["booker_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_resource_id_fkey"
            columns: ["resource_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id"]
          },
        ]
      }
      clubhouse_checklist_runs: {
        Row: {
          checklist_id: string
          completed_at: string | null
          completed_by: string | null
          id: string
          item_states: Json
          notes: string | null
          week_start: string
        }
        Insert: {
          checklist_id: string
          completed_at?: string | null
          completed_by?: string | null
          id?: string
          item_states?: Json
          notes?: string | null
          week_start: string
        }
        Update: {
          checklist_id?: string
          completed_at?: string | null
          completed_by?: string | null
          id?: string
          item_states?: Json
          notes?: string | null
          week_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "clubhouse_checklist_runs_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "clubhouse_checklists"
            referencedColumns: ["id"]
          },
        ]
      }
      clubhouse_checklists: {
        Row: {
          active: boolean
          assignees: Json
          created_at: string
          description: string | null
          id: string
          items: Json
          sort_order: number
          title: string
        }
        Insert: {
          active?: boolean
          assignees?: Json
          created_at?: string
          description?: string | null
          id?: string
          items?: Json
          sort_order?: number
          title: string
        }
        Update: {
          active?: boolean
          assignees?: Json
          created_at?: string
          description?: string | null
          id?: string
          items?: Json
          sort_order?: number
          title?: string
        }
        Relationships: []
      }
      clubhouse_project_notes: {
        Row: {
          author_id: string | null
          author_name: string | null
          body: string
          created_at: string
          id: string
          project_id: string
        }
        Insert: {
          author_id?: string | null
          author_name?: string | null
          body: string
          created_at?: string
          id?: string
          project_id: string
        }
        Update: {
          author_id?: string | null
          author_name?: string | null
          body?: string
          created_at?: string
          id?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "clubhouse_project_notes_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "clubhouse_projects"
            referencedColumns: ["id"]
          },
        ]
      }
      clubhouse_projects: {
        Row: {
          assigned_to_id: string | null
          assigned_to_name: string | null
          cost_pence: number
          created_at: string
          created_by: string | null
          description: string | null
          due_date: string | null
          id: string
          importance: string
          progress: string
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          assigned_to_id?: string | null
          assigned_to_name?: string | null
          cost_pence?: number
          created_at?: string
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          importance?: string
          progress?: string
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          assigned_to_id?: string | null
          assigned_to_name?: string | null
          cost_pence?: number
          created_at?: string
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          importance?: string
          progress?: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      email_templates: {
        Row: {
          body_html: string | null
          created_at: string
          id: string
          key: string
          name: string
          subject: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          body_html?: string | null
          created_at?: string
          id?: string
          key: string
          name: string
          subject?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          body_html?: string | null
          created_at?: string
          id?: string
          key?: string
          name?: string
          subject?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      faqs: {
        Row: {
          active: boolean
          answer: string
          created_at: string
          id: string
          question: string
          sort_order: number
        }
        Insert: {
          active?: boolean
          answer: string
          created_at?: string
          id?: string
          question: string
          sort_order?: number
        }
        Update: {
          active?: boolean
          answer?: string
          created_at?: string
          id?: string
          question?: string
          sort_order?: number
        }
        Relationships: []
      }
      function_rooms: {
        Row: {
          active: boolean
          capacity: number | null
          created_at: string
          description: string | null
          extra_hour_pence: number | null
          extras_config: Json
          id: string
          information: string | null
          name: string
          price_note: string | null
          price_pence_fixed: number | null
          price_pence_full_day: number | null
          price_pence_half_day: number | null
          price_pence_per_hour: number | null
          resources: string[]
          sort_order: number
          standard_hours: number | null
          standard_price_pence: number | null
        }
        Insert: {
          active?: boolean
          capacity?: number | null
          created_at?: string
          description?: string | null
          extra_hour_pence?: number | null
          extras_config?: Json
          id?: string
          information?: string | null
          name: string
          price_note?: string | null
          price_pence_fixed?: number | null
          price_pence_full_day?: number | null
          price_pence_half_day?: number | null
          price_pence_per_hour?: number | null
          resources?: string[]
          sort_order?: number
          standard_hours?: number | null
          standard_price_pence?: number | null
        }
        Update: {
          active?: boolean
          capacity?: number | null
          created_at?: string
          description?: string | null
          extra_hour_pence?: number | null
          extras_config?: Json
          id?: string
          information?: string | null
          name?: string
          price_note?: string | null
          price_pence_fixed?: number | null
          price_pence_full_day?: number | null
          price_pence_half_day?: number | null
          price_pence_per_hour?: number | null
          resources?: string[]
          sort_order?: number
          standard_hours?: number | null
          standard_price_pence?: number | null
        }
        Relationships: []
      }
      guardian_consents: {
        Row: {
          child_person_id: string
          consent_type: Database["public"]["Enums"]["consent_type"]
          expires_at: string | null
          granted_at: string
          granted_by: string | null
          guardian_person_id: string
          id: string
          notes: string | null
          notice_version: string
          revoked_at: string | null
          revoked_by: string | null
          updated_at: string
        }
        Insert: {
          child_person_id: string
          consent_type: Database["public"]["Enums"]["consent_type"]
          expires_at?: string | null
          granted_at?: string
          granted_by?: string | null
          guardian_person_id: string
          id?: string
          notes?: string | null
          notice_version: string
          revoked_at?: string | null
          revoked_by?: string | null
          updated_at?: string
        }
        Update: {
          child_person_id?: string
          consent_type?: Database["public"]["Enums"]["consent_type"]
          expires_at?: string | null
          granted_at?: string
          granted_by?: string | null
          guardian_person_id?: string
          id?: string
          notes?: string | null
          notice_version?: string
          revoked_at?: string | null
          revoked_by?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "guardian_consents_child_person_id_fkey"
            columns: ["child_person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "guardian_consents_guardian_person_id_fkey"
            columns: ["guardian_person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
        ]
      }
      guardianships: {
        Row: {
          child_person_id: string
          created_at: string
          created_by: string | null
          ended_at: string | null
          guardian_person_id: string
          id: string
          notes: string | null
          relationship: Database["public"]["Enums"]["guardian_relationship"]
          updated_at: string
        }
        Insert: {
          child_person_id: string
          created_at?: string
          created_by?: string | null
          ended_at?: string | null
          guardian_person_id: string
          id?: string
          notes?: string | null
          relationship: Database["public"]["Enums"]["guardian_relationship"]
          updated_at?: string
        }
        Update: {
          child_person_id?: string
          created_at?: string
          created_by?: string | null
          ended_at?: string | null
          guardian_person_id?: string
          id?: string
          notes?: string | null
          relationship?: Database["public"]["Enums"]["guardian_relationship"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "guardianships_child_person_id_fkey"
            columns: ["child_person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "guardianships_guardian_person_id_fkey"
            columns: ["guardian_person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
        ]
      }
      holiday_requests: {
        Row: {
          created_at: string
          from_date: string
          id: string
          note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          reviewer_name: string | null
          reviewer_note: string | null
          staff_name: string
          staff_profile_id: string | null
          status: string
          to_date: string
        }
        Insert: {
          created_at?: string
          from_date: string
          id?: string
          note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_name?: string | null
          reviewer_note?: string | null
          staff_name: string
          staff_profile_id?: string | null
          status?: string
          to_date: string
        }
        Update: {
          created_at?: string
          from_date?: string
          id?: string
          note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_name?: string | null
          reviewer_note?: string | null
          staff_name?: string
          staff_profile_id?: string | null
          status?: string
          to_date?: string
        }
        Relationships: []
      }
      non_user_staff: {
        Row: {
          active: boolean
          bar_contracted_hours: number | null
          bar_hourly_rate_pence: number | null
          bar_overtime_rate_pence: number | null
          bar_pay_type: string | null
          created_at: string
          id: string
          name: string
        }
        Insert: {
          active?: boolean
          bar_contracted_hours?: number | null
          bar_hourly_rate_pence?: number | null
          bar_overtime_rate_pence?: number | null
          bar_pay_type?: string | null
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          active?: boolean
          bar_contracted_hours?: number | null
          bar_hourly_rate_pence?: number | null
          bar_overtime_rate_pence?: number | null
          bar_pay_type?: string | null
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount_pence: number
          authorised_by_email: string | null
          authorised_by_name: string | null
          authorised_by_profile: string | null
          booking_id: string
          created_at: string
          id: string
          legacy_booking_payment_id: string | null
          method: string | null
          note: string | null
          paid_at: string
          reference: string | null
          source: string
          stripe_payment_intent_id: string | null
          sumup_checkout_id: string | null
          sumup_txn_code: string | null
        }
        Insert: {
          amount_pence: number
          authorised_by_email?: string | null
          authorised_by_name?: string | null
          authorised_by_profile?: string | null
          booking_id: string
          created_at?: string
          id?: string
          legacy_booking_payment_id?: string | null
          method?: string | null
          note?: string | null
          paid_at?: string
          reference?: string | null
          source?: string
          stripe_payment_intent_id?: string | null
          sumup_checkout_id?: string | null
          sumup_txn_code?: string | null
        }
        Update: {
          amount_pence?: number
          authorised_by_email?: string | null
          authorised_by_name?: string | null
          authorised_by_profile?: string | null
          booking_id?: string
          created_at?: string
          id?: string
          legacy_booking_payment_id?: string | null
          method?: string | null
          note?: string | null
          paid_at?: string
          reference?: string | null
          source?: string
          stripe_payment_intent_id?: string | null
          sumup_checkout_id?: string | null
          sumup_txn_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_authorised_by_profile_fkey"
            columns: ["authorised_by_profile"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      people: {
        Row: {
          address: Json | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          deleted_by: string | null
          dob: string | null
          email: string | null
          first_name: string
          id: string
          last_name: string
          legal_hold: boolean
          notes: string | null
          phone: string | null
          preferred_name: string | null
          pseudonymised_at: string | null
          updated_at: string
        }
        Insert: {
          address?: Json | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
          dob?: string | null
          email?: string | null
          first_name: string
          id?: string
          last_name: string
          legal_hold?: boolean
          notes?: string | null
          phone?: string | null
          preferred_name?: string | null
          pseudonymised_at?: string | null
          updated_at?: string
        }
        Update: {
          address?: Json | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
          dob?: string | null
          email?: string | null
          first_name?: string
          id?: string
          last_name?: string
          legal_hold?: boolean
          notes?: string | null
          phone?: string | null
          preferred_name?: string | null
          pseudonymised_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      person_roles: {
        Row: {
          granted_at: string
          granted_by: string | null
          id: string
          notes: string | null
          person_id: string
          revoked_at: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
        }
        Insert: {
          granted_at?: string
          granted_by?: string | null
          id?: string
          notes?: string | null
          person_id: string
          revoked_at?: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Update: {
          granted_at?: string
          granted_by?: string | null
          id?: string
          notes?: string | null
          person_id?: string
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "person_roles_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          bar_contracted_hours: number | null
          bar_hourly_rate_pence: number | null
          bar_overtime_rate_pence: number | null
          bar_pay_type: string | null
          created_at: string
          full_name: string | null
          holiday_allowance_days: number | null
          id: string
          person_id: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          bar_contracted_hours?: number | null
          bar_hourly_rate_pence?: number | null
          bar_overtime_rate_pence?: number | null
          bar_pay_type?: string | null
          created_at?: string
          full_name?: string | null
          holiday_allowance_days?: number | null
          id: string
          person_id: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          bar_contracted_hours?: number | null
          bar_hourly_rate_pence?: number | null
          bar_overtime_rate_pence?: number | null
          bar_pay_type?: string | null
          created_at?: string
          full_name?: string | null
          holiday_allowance_days?: number | null
          id?: string
          person_id?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: [
          {
            foreignKeyName: "profiles_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: true
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
        ]
      }
      resources: {
        Row: {
          active: boolean
          amenities: string[]
          capacity: number | null
          created_at: string
          default_post_buffer_minutes: number
          default_pre_buffer_minutes: number
          description: string | null
          extra_hour_pence: number | null
          extras_config: Json
          id: string
          information: string | null
          legacy_function_room_id: string | null
          name: string
          price_note: string | null
          price_pence_fixed: number | null
          price_pence_full_day: number | null
          price_pence_half_day: number | null
          price_pence_per_hour: number | null
          sort_order: number
          standard_hours: number | null
          standard_price_pence: number | null
          type: Database["public"]["Enums"]["resource_type"]
          updated_at: string
        }
        Insert: {
          active?: boolean
          amenities?: string[]
          capacity?: number | null
          created_at?: string
          default_post_buffer_minutes?: number
          default_pre_buffer_minutes?: number
          description?: string | null
          extra_hour_pence?: number | null
          extras_config?: Json
          id?: string
          information?: string | null
          legacy_function_room_id?: string | null
          name: string
          price_note?: string | null
          price_pence_fixed?: number | null
          price_pence_full_day?: number | null
          price_pence_half_day?: number | null
          price_pence_per_hour?: number | null
          sort_order?: number
          standard_hours?: number | null
          standard_price_pence?: number | null
          type: Database["public"]["Enums"]["resource_type"]
          updated_at?: string
        }
        Update: {
          active?: boolean
          amenities?: string[]
          capacity?: number | null
          created_at?: string
          default_post_buffer_minutes?: number
          default_pre_buffer_minutes?: number
          description?: string | null
          extra_hour_pence?: number | null
          extras_config?: Json
          id?: string
          information?: string | null
          legacy_function_room_id?: string | null
          name?: string
          price_note?: string | null
          price_pence_fixed?: number | null
          price_pence_full_day?: number | null
          price_pence_half_day?: number | null
          price_pence_per_hour?: number | null
          sort_order?: number
          standard_hours?: number | null
          standard_price_pence?: number | null
          type?: Database["public"]["Enums"]["resource_type"]
          updated_at?: string
        }
        Relationships: []
      }
      room_bookings: {
        Row: {
          amount_pence: number | null
          anonymised_at: string | null
          balance_due_date: string | null
          balance_reminder_sent_at: string | null
          base_hire_pence: number
          booker_email: string
          booker_first_name: string | null
          booker_last_name: string | null
          booker_name: string
          booker_phone: string | null
          booker_profile_id: string | null
          booking_type: string
          calendar_event_id: string | null
          cancellation_warning_sent_at: string | null
          child_name: string | null
          child_team: string | null
          confirmation_note: string | null
          created_at: string
          date: string
          deposit_due_date: string | null
          deposit_pence: number | null
          deposit_reminder_sent_at: string | null
          deposit_terms_accepted_at: string | null
          end_time: string
          estimated_guests: number | null
          extras_total_pence: number
          id: string
          internal_notes: string | null
          is_member: boolean
          member_discount_pence: number
          member_number: string | null
          membership_type: string | null
          notes: string | null
          occasion: string | null
          payment_method: string | null
          payment_received_at: string | null
          payment_received_by: string | null
          payment_reference: string | null
          payment_status: string
          quote_followup_sent_at: string | null
          recurrence_group_id: string | null
          room_id: string
          security_deposit_nudge_sent_at: string | null
          security_deposit_pence: number
          security_deposit_returned_at: string | null
          security_deposit_returned_method: string | null
          security_deposit_returned_note: string | null
          selected_extras: Json
          start_time: string
          status: string
          stripe_checkout_id: string | null
          stripe_ref: string | null
          team_name: string | null
          thank_you_sent_at: string | null
          total_pence: number | null
          updated_at: string
        }
        Insert: {
          amount_pence?: number | null
          anonymised_at?: string | null
          balance_due_date?: string | null
          balance_reminder_sent_at?: string | null
          base_hire_pence?: number
          booker_email: string
          booker_first_name?: string | null
          booker_last_name?: string | null
          booker_name: string
          booker_phone?: string | null
          booker_profile_id?: string | null
          booking_type?: string
          calendar_event_id?: string | null
          cancellation_warning_sent_at?: string | null
          child_name?: string | null
          child_team?: string | null
          confirmation_note?: string | null
          created_at?: string
          date: string
          deposit_due_date?: string | null
          deposit_pence?: number | null
          deposit_reminder_sent_at?: string | null
          deposit_terms_accepted_at?: string | null
          end_time: string
          estimated_guests?: number | null
          extras_total_pence?: number
          id?: string
          internal_notes?: string | null
          is_member?: boolean
          member_discount_pence?: number
          member_number?: string | null
          membership_type?: string | null
          notes?: string | null
          occasion?: string | null
          payment_method?: string | null
          payment_received_at?: string | null
          payment_received_by?: string | null
          payment_reference?: string | null
          payment_status?: string
          quote_followup_sent_at?: string | null
          recurrence_group_id?: string | null
          room_id: string
          security_deposit_nudge_sent_at?: string | null
          security_deposit_pence?: number
          security_deposit_returned_at?: string | null
          security_deposit_returned_method?: string | null
          security_deposit_returned_note?: string | null
          selected_extras?: Json
          start_time: string
          status?: string
          stripe_checkout_id?: string | null
          stripe_ref?: string | null
          team_name?: string | null
          thank_you_sent_at?: string | null
          total_pence?: number | null
          updated_at?: string
        }
        Update: {
          amount_pence?: number | null
          anonymised_at?: string | null
          balance_due_date?: string | null
          balance_reminder_sent_at?: string | null
          base_hire_pence?: number
          booker_email?: string
          booker_first_name?: string | null
          booker_last_name?: string | null
          booker_name?: string
          booker_phone?: string | null
          booker_profile_id?: string | null
          booking_type?: string
          calendar_event_id?: string | null
          cancellation_warning_sent_at?: string | null
          child_name?: string | null
          child_team?: string | null
          confirmation_note?: string | null
          created_at?: string
          date?: string
          deposit_due_date?: string | null
          deposit_pence?: number | null
          deposit_reminder_sent_at?: string | null
          deposit_terms_accepted_at?: string | null
          end_time?: string
          estimated_guests?: number | null
          extras_total_pence?: number
          id?: string
          internal_notes?: string | null
          is_member?: boolean
          member_discount_pence?: number
          member_number?: string | null
          membership_type?: string | null
          notes?: string | null
          occasion?: string | null
          payment_method?: string | null
          payment_received_at?: string | null
          payment_received_by?: string | null
          payment_reference?: string | null
          payment_status?: string
          quote_followup_sent_at?: string | null
          recurrence_group_id?: string | null
          room_id?: string
          security_deposit_nudge_sent_at?: string | null
          security_deposit_pence?: number
          security_deposit_returned_at?: string | null
          security_deposit_returned_method?: string | null
          security_deposit_returned_note?: string | null
          selected_extras?: Json
          start_time?: string
          status?: string
          stripe_checkout_id?: string | null
          stripe_ref?: string | null
          team_name?: string | null
          thank_you_sent_at?: string | null
          total_pence?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_bookings_booker_profile_id_fkey"
            columns: ["booker_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_bookings_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "function_rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      sickness_records: {
        Row: {
          created_at: string
          created_by: string | null
          from_date: string
          id: string
          non_user_staff_id: string | null
          note: string | null
          staff_name: string
          staff_profile_id: string | null
          to_date: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          from_date: string
          id?: string
          non_user_staff_id?: string | null
          note?: string | null
          staff_name: string
          staff_profile_id?: string | null
          to_date?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          from_date?: string
          id?: string
          non_user_staff_id?: string | null
          note?: string | null
          staff_name?: string
          staff_profile_id?: string | null
          to_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sickness_records_non_user_staff_id_fkey"
            columns: ["non_user_staff_id"]
            isOneToOne: false
            referencedRelation: "non_user_staff"
            referencedColumns: ["id"]
          },
        ]
      }
      site_settings: {
        Row: {
          key: string
          updated_at: string
          value: string
        }
        Insert: {
          key: string
          updated_at?: string
          value?: string
        }
        Update: {
          key?: string
          updated_at?: string
          value?: string
        }
        Relationships: []
      }
      staff_away: {
        Row: {
          created_at: string
          created_by: string | null
          from_date: string
          id: string
          non_user_staff_id: string | null
          note: string | null
          staff_id: string | null
          to_date: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          from_date: string
          id?: string
          non_user_staff_id?: string | null
          note?: string | null
          staff_id?: string | null
          to_date: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          from_date?: string
          id?: string
          non_user_staff_id?: string | null
          note?: string | null
          staff_id?: string | null
          to_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "staff_away_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "staff_away_non_user_staff_id_fkey"
            columns: ["non_user_staff_id"]
            isOneToOne: false
            referencedRelation: "non_user_staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "staff_away_staff_id_fkey"
            columns: ["staff_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      timesheet_shifts: {
        Row: {
          break_minutes: number
          created_at: string
          end_time: string
          hourly_rate_pence: number
          id: string
          is_overtime: boolean
          non_user_staff_id: string | null
          note: string | null
          staff_name: string
          staff_profile_id: string | null
          start_time: string
          timesheet_id: string
          work_date: string
          work_type: string
        }
        Insert: {
          break_minutes?: number
          created_at?: string
          end_time: string
          hourly_rate_pence?: number
          id?: string
          is_overtime?: boolean
          non_user_staff_id?: string | null
          note?: string | null
          staff_name: string
          staff_profile_id?: string | null
          start_time: string
          timesheet_id: string
          work_date: string
          work_type?: string
        }
        Update: {
          break_minutes?: number
          created_at?: string
          end_time?: string
          hourly_rate_pence?: number
          id?: string
          is_overtime?: boolean
          non_user_staff_id?: string | null
          note?: string | null
          staff_name?: string
          staff_profile_id?: string | null
          start_time?: string
          timesheet_id?: string
          work_date?: string
          work_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "timesheet_shifts_non_user_staff_id_fkey"
            columns: ["non_user_staff_id"]
            isOneToOne: false
            referencedRelation: "non_user_staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "timesheet_shifts_timesheet_id_fkey"
            columns: ["timesheet_id"]
            isOneToOne: false
            referencedRelation: "timesheets"
            referencedColumns: ["id"]
          },
        ]
      }
      timesheets: {
        Row: {
          created_at: string
          id: string
          reviewed_at: string | null
          reviewed_by: string | null
          reviewer_note: string | null
          status: string
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          week_start: string
        }
        Insert: {
          created_at?: string
          id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_note?: string | null
          status?: string
          submitted_at?: string | null
          submitted_by?: string | null
          updated_at?: string
          week_start: string
        }
        Update: {
          created_at?: string
          id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_note?: string | null
          status?: string
          submitted_at?: string | null
          submitted_by?: string | null
          updated_at?: string
          week_start?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      backfill_person_roles: {
        Args: never
        Returns: {
          roles_created: number
        }[]
      }
      backfill_profiles_people: {
        Args: never
        Returns: {
          people_created: number
          people_ids: string[]
          profiles_linked: number
        }[]
      }
      booking_conflicts: {
        Args: {
          p_ends_at: string
          p_exclude_booking_id?: string
          p_post_buffer_minutes?: number
          p_pre_buffer_minutes?: number
          p_resource_id: string
          p_starts_at: string
        }
        Returns: {
          anonymised_at: string | null
          balance_due_date: string | null
          balance_reminder_sent_at: string | null
          base_hire_pence: number
          blocked_from: string
          blocked_until: string
          booker_email: string
          booker_first_name: string | null
          booker_last_name: string | null
          booker_name: string
          booker_person_id: string | null
          booker_phone: string | null
          booker_profile_id: string | null
          calendar_event_id: string | null
          cancellation_warning_sent_at: string | null
          child_name: string | null
          child_team: string | null
          confirmation_note: string | null
          created_at: string
          created_by: string | null
          deposit_due_date: string | null
          deposit_pence: number | null
          deposit_reminder_sent_at: string | null
          deposit_terms_accepted_at: string | null
          ends_at: string
          estimated_guests: number | null
          extras_total_pence: number
          id: string
          internal_notes: string | null
          is_member: boolean
          kind: Database["public"]["Enums"]["booking_kind"]
          legacy_room_booking_id: string | null
          member_discount_pence: number
          member_number: string | null
          membership_type: string | null
          notes: string | null
          occasion: string | null
          payment_method: string | null
          payment_received_at: string | null
          payment_received_by: string | null
          payment_reference: string | null
          payment_status: Database["public"]["Enums"]["payment_status"]
          post_buffer_minutes: number
          pre_buffer_minutes: number
          quote_followup_sent_at: string | null
          recurrence_group_id: string | null
          resource_id: string
          security_deposit_nudge_sent_at: string | null
          security_deposit_pence: number
          security_deposit_returned_at: string | null
          security_deposit_returned_method: string | null
          security_deposit_returned_note: string | null
          selected_extras: Json
          starts_at: string
          status: Database["public"]["Enums"]["booking_status"]
          stripe_checkout_id: string | null
          stripe_ref: string | null
          team_name: string | null
          thank_you_sent_at: string | null
          total_pence: number | null
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "bookings"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      booking_has_conflict: {
        Args: {
          p_ends_at: string
          p_exclude_booking_id?: string
          p_post_buffer_minutes?: number
          p_pre_buffer_minutes?: number
          p_resource_id: string
          p_starts_at: string
        }
        Returns: boolean
      }
      current_person_id: { Args: never; Returns: string }
      has_active_consent: {
        Args: {
          p_child_person_id: string
          p_consent_type: Database["public"]["Enums"]["consent_type"]
        }
        Returns: boolean
      }
      has_any_role: {
        Args: { p_roles: Database["public"]["Enums"]["app_role"][] }
        Returns: boolean
      }
      has_role: {
        Args: { p_role: Database["public"]["Enums"]["app_role"] }
        Returns: boolean
      }
      is_account_eligible: { Args: { p_person_id: string }; Returns: boolean }
      is_at_least_age: {
        Args: { d: string; p_years: number }
        Returns: boolean
      }
      is_bar_manager: { Args: never; Returns: boolean }
      is_club_admin: { Args: never; Returns: boolean }
      is_committee: { Args: never; Returns: boolean }
      is_minor: { Args: { person_id: string }; Returns: boolean }
      is_minor_dob: { Args: { d: string }; Returns: boolean }
      is_safeguarding_lead: { Args: never; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
      is_supervision_exempt: { Args: { p_person_id: string }; Returns: boolean }
      map_user_role_to_app_role: {
        Args: { p_role: Database["public"]["Enums"]["user_role"] }
        Returns: Database["public"]["Enums"]["app_role"]
      }
      map_user_role_to_app_role_strict: {
        Args: { p_role: Database["public"]["Enums"]["user_role"] }
        Returns: Database["public"]["Enums"]["app_role"]
      }
      migrate_room_bookings: {
        Args: never
        Returns: {
          bookings_removed: number
          bookings_upserted: number
          comms_upserted: number
          payments_upserted: number
          resources_upserted: number
        }[]
      }
      person_has_role: {
        Args: {
          p_person_id: string
          p_role: Database["public"]["Enums"]["app_role"]
        }
        Returns: boolean
      }
      reconcile_room_bookings: {
        Args: never
        Returns: {
          check: string
          legacy: number
          ok: boolean
          unified: number
        }[]
      }
      safeguarding_setting_int: { Args: { p_key: string }; Returns: number }
      split_person_name: {
        Args: { p_full_name: string }
        Returns: {
          first_name: string
          last_name: string
        }[]
      }
      write_audit: {
        Args: {
          p_action: string
          p_detail?: Json
          p_entity: string
          p_entity_id?: string
        }
        Returns: number
      }
    }
    Enums: {
      app_role:
        | "club_admin"
        | "safeguarding_lead"
        | "coach"
        | "staff"
        | "member"
        | "parent"
        | "hirer"
      booking_kind: "hire" | "block" | "fixture" | "maintenance"
      booking_status:
        | "enquiry"
        | "quoted"
        | "pending"
        | "confirmed"
        | "cancelled"
      consent_type: "app_account" | "unsupervised_messaging"
      guardian_relationship:
        | "parent"
        | "step_parent"
        | "grandparent"
        | "foster_carer"
        | "legal_guardian"
        | "other"
      payment_status: "unpaid" | "deposit_paid" | "paid"
      resource_type: "function_room" | "pitch"
      user_role:
        | "committee"
        | "bar"
        | "bar_manager"
        | "member"
        | "super_user"
        | "staff"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: [
        "club_admin",
        "safeguarding_lead",
        "coach",
        "staff",
        "member",
        "parent",
        "hirer",
      ],
      booking_kind: ["hire", "block", "fixture", "maintenance"],
      booking_status: [
        "enquiry",
        "quoted",
        "pending",
        "confirmed",
        "cancelled",
      ],
      consent_type: ["app_account", "unsupervised_messaging"],
      guardian_relationship: [
        "parent",
        "step_parent",
        "grandparent",
        "foster_carer",
        "legal_guardian",
        "other",
      ],
      payment_status: ["unpaid", "deposit_paid", "paid"],
      resource_type: ["function_room", "pitch"],
      user_role: [
        "committee",
        "bar",
        "bar_manager",
        "member",
        "super_user",
        "staff",
      ],
    },
  },
} as const

