/**
 * Local schools offered on the public waiting list form (P3.4).
 *
 * Carried over from the pitch-booking app so a parent picks the same school
 * name they would have before the cutover. The column is free text: anything
 * not on this list arrives through the "Other" box.
 */

export const SCHOOL_LIST = [
  "Abbotsford Preparatory School",
  "Acre Hall Primary School",
  "All Saints Catholic Primary School",
  "Altrincham CofE (Aided) Primary School",
  "Altrincham College",
  "Altrincham Grammar School for Boys",
  "Altrincham Grammar School for Girls",
  "Altrincham Preparatory School",
  "Ashton-on-Mersey School",
  "Barton Clough Primary School",
  "Blessed Thomas Holford Catholic College",
  "Bollin Primary School",
  "Bowdon CofE Primary School",
  "Bowdon Preparatory School",
  "Brentwood School",
  "Broadheath Primary School",
  "Broadoak School",
  "Brooklands Primary School",
  "Broomwood Primary School",
  "Cloverlea Primary School",
  "Davyhulme Primary School",
  "Delamere School",
  "Egerton High School",
  "Elmridge Primary School",
  "English Martyrs' RC Primary School",
  "Firs Primary School",
  "Flixton Girls School",
  "Flixton Primary School",
  "Forest Gate Academy",
  "Forest Park Preparatory School",
  "Forest School",
  "Gorse Hill Primary School",
  "Hale Preparatory School",
  "Heyes Lane Primary School",
  "Highfield Primary School",
  "Holy Family Catholic Primary School",
  "Kingsway Primary School",
  "Lime Tree Primary Academy",
  "Little Bollington CofE Primary School",
  "Longford Park School",
  "Loreto Grammar School",
  "Lostock High School",
  "Manor Academy Sale",
  "Moorlands Junior School",
  "Moss Park Primary School",
  "Navigation Primary School",
  "North Cestrian School",
  "Oldfield Brow Primary School",
  "Our Lady of the Rosary RC Primary School",
  "Park Road Academy Primary School",
  "Park Road Sale Primary School",
  "Partington Central Academy",
  "Pictor Academy",
  "Saint Ambrose College",
  "Sale Grammar School",
  "Sale High School",
  "Springfield Primary School",
  "St Ambrose Preparatory School",
  "St Anne's CofE Primary School",
  "St Ann's RC Primary School",
  "St Antony's RC School",
  "St Hugh of Lincoln RC Primary School",
  "St Hugh's Catholic Primary School",
  "St Joseph's Catholic Primary School",
  "St Margaret Ward Catholic Primary School",
  "St Mary's CofE Primary School",
  "St Matthew's CofE Primary School",
  "St Michael's CofE Primary School",
  "St Monica's RC Primary School",
  "St Vincent's Catholic Primary School",
  "Stamford Park Primary School",
  "Stretford Grammar School",
  "Stretford High School",
  "Templemoor Infant and Nursery School",
  "The Orchards",
  "Tyntesfield Primary School",
  "Urmston Grammar Academy",
  "Urmston Primary School",
  "Victoria Park Infant School",
  "Victoria Park Junior School",
  "Well Green Primary School",
  "Wellacre Technology Academy",
  "Wellfield Infant and Nursery School",
  "Wellfield Junior School",
  "Wellington School",
  "Willows Primary School",
  "Woodheys Primary School",
  "Woodhouse Primary School",
  "Worthington Primary School",
] as const;
